/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    FloatingSearchBox: typeof import('./src/components/search/FloatingSearchBox.vue')['default']
    MultiModalIndicator: typeof import('./src/components/search/MultiModalIndicator.vue')['default']
    ResultCard: typeof import('./src/components/search/ResultCard.vue')['default']
    ResultCardSkeleton: typeof import('./src/components/search/ResultCardSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
